version: '2'
services:
  registry:
    image: registry
    ports:
      - "50051:50051"
      - "8080:8080"
  pokedex:
    image: pokedex
    ports:
      - "50052:50051"
      - "8081:8080"
    links:
      - registry
  warden:
    image: warden
    ports:
      - "50053:50051"
      - "8082:8080"
    links:
      - registry
      - pokedex
