apiVersion: v1
kind: Service
metadata:
  name: pokedex
  labels:
    app: pokedex
spec:
  ports:
    - port: 50051
      name: grpc
    - port: 8080
      name: http
  selector:
    app: pokedex
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pokedex
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      containers:
      - name: pokedex
        image: safari/pokedex
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        #env:
        ports:
        - containerPort: 50051
        - containerPort: 8080
        imagePullPolicy: Never
