apiVersion: v1
kind: Service
metadata:
  name: pokedex
  labels:
    app: pokedex
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 50051
      nodePort: 30052
    - name: http
      port: 8080
      nodePort: 30082
  selector:
    app: pokedex
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pokedex
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      containers:
      - name: pokedex
        image: safari/pokedex
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        #env:
        #- name: GET_HOSTS_FROM
        #  value: dns
        ports:
        - containerPort: 50051
        - containerPort: 8080
        imagePullPolicy: Never
