apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
    - port: 50051
      name: grpc
      protocol: tcp
    - port: 8080
      name: http
      protocol: tcp
  selector:
    app: registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  # labels:
  #   app: redis
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: safari/registry
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 50051
        - containerPort: 8080
        imagePullPolicy: Never
