apiVersion: v1
kind: Service
metadata:
  name: warden
  labels:
    app: warden
spec:
  ports:
    - port: 50051
      name: grpc
    - port: 8080
      name: http
  selector:
    app: warden
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: warden
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: warden
    spec:
      containers:
      - name: warden
        image: safari/warden
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        #env:
        #- name: GET_HOSTS_FROM
        #  value: dns
        ports:
        - containerPort: 50051
        - containerPort: 8080
        imagePullPolicy: Never
